language: objective-c
os: osx

install:
  - sudo pip install -U -I pip
  - sudo pip install -U -I numpy
  
script:
  - system_profiler -detailLevel basic | grep -A20 'Hardware Overview:'
  - which python
  - python nptest.py